apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Learn
  SPRING_DATASOURCE_USERNAME: postgres
  OAUTH_REDIRECT_URI: https://wisdomless-damien-thorniest.ngrok-free.dev/login/oauth2/code/google
  CORS_ALLOWED_ORIGINS: https://wisdomless-damien-thorniest.ngrok-free.dev
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "123"
  GOOGLE_CLIENT_ID: "876160915255-ekck224okup549a5mk8pqiqlf888ci06.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-backend
  template:
    metadata:
      labels:
        app: java-backend
    spec:
      containers:
        - name: java-backend
          image: rjram/expense-part2-backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret

---
apiVersion: v1
kind: Service
metadata:
  name: java-backend
spec:
  selector:
    app: java-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
